services:

  mongo1:
    image: mongo:8
    container_name: mongo1
    ports:
      - "27017:27017"
    volumes:
      - mongo1_data:/data/db

  mongo2:
    image: mongo:8
    container_name: mongo2
    ports:
      - "27018:27017"
    volumes:
      - mongo2_data:/data/db

  mongo3:
    image: mongo:8
    container_name: mongo3
    ports:
      - "27019:27017"
    volumes:
      - mongo3_data:/data/db

  mongo4:
    image: mongo:8
    container_name: mongo4
    ports:
      - "27020:27017"
    volumes:
      - mongo4_data:/data/db

volumes:
  mongo1_data:
  mongo2_data:
  mongo3_data:
  mongo4_data:
